# -*- coding: utf-8 -*-
"""winequality prediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LyIow2WdXiK6bywaZ2_hdWAVgG8u1xsx

**Installing Libraries**
"""

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
from google.colab import drive
drive.mount('/content/drive')

"""**Importing the Dataset**"""

data = pd.read_csv("/content/drive/MyDrive/winequality.csv")

data.head()

data.columns

data.describe()

data.info()

data.isnull().sum()

data['quality'].value_counts()

"""**Data Visualization**

**Bivariate Analysis**
"""

# checking the variation of fixed acidity in the different qualities of wine

plt.scatter(data['quality'], data['fixed acidity'], color = 'green')
plt.title('relation of fixed acidity with wine')
plt.xlabel('quality')
plt.ylabel('fixed acidity')
plt.legend()
plt.show()

"""As we can see that like the above two items do not have very strong relation to the dependent variable we have to showcase a correlation plot to check which of the items are more related to the dependent variable and which items are less related to the dependent variables.

From the above correlation plot for the given dataset for wine quality prediction, we can easily see which items are related strongly with each other and which items are related weekly with each other.
For Example,
# The strongly correlated items are :

1.fixed acidity and citric acid.
2.free sulphur dioxide and total sulphor dioxide.
3.fixed acidity and density.
4. alcohol and quality.

so, from above points there is a clear inference that alcohol is the most important characteristic to determine the quality of wine.

# The weekly correlated items are :

1.citric acid and volatile acidity.
2.fixed acidity and ph.
3.density and alcohol.

These are some relations which do not depend on each other at all.
"""

import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Generate a 10x10 matrix of random numbers
np.random.seed(42)
data = np.random.rand(10, 10)  # Values between 0 and 1

# Create the heatmap
plt.figure(figsize=(8, 6))
sns.heatmap(data, annot=True, linewidths=2.0)

# Add title
plt.title("Heatmap Example")

# Show the plot
plt.show()

"""**Data pre-processing**"""

# Removing Unnecassary columns from the dataset
# As we saw that volatile acidity, total sulphor dioxide, chlorides, density are very less related to the dependent variable
#   quality so even if we remove these columns the accuracy won't be affected that much.

#data = data.drop(['volatile acidity', 'total sulfur dioxide', 'chlorides', 'density'], axis = 1)

# checking the shape of the dataset
#print(data.shape)



data.columns

# converting the response variables(3-7) as binary response variables that is either good or bad

#names = ['bad', 'good']
#bins = (2, 6.5, 8)

#data['quality'] = pd.cut(data['quality'], bins = bins, labels = names)

data['quality1'] = data['quality'].map({3 : 'bad', 4 :'bad', 5: 'bad',
                                      6: 'good', 7: 'good', 8: 'good'})

# analyzing the different values present in the dependent variable(quality column)
data['quality1'] = data['quality'].map({3 : 'bad', 4 :'bad', 5: 'bad',
                                         6: 'good', 7: 'good', 8: 'good'})
data['quality1'].value_counts()

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

data['quality'] = le.fit_transform(data['quality'])

data['quality'].value_counts

sns.countplot(data['quality'])

"""# **Correlation Analysis**
You're checking how strongly each feature (like alcohol, acidity, sulphates) is related to wine quality.
- Pearson correlation tells you how linearly related two variables are.
- Spearman correlation tells you how monotonically related they are (i.e., if one increases, does the other also increase, regardless of exact shape).
✅ This helps you quantify relationships between features and the target variable.

"""

import pandas as pd
from scipy.stats import pearsonr, spearmanr, ttest_ind
import seaborn as sns
import matplotlib.pyplot as plt


from google.colab import drive
drive.mount('/content/drive')

# Load your dataset
data = pd.read_csv("/content/drive/MyDrive/winequality.csv")

# Convert quality to binary (if not already done)
data['quality'] = data['quality'].map({3: 'bad', 4: 'bad', 5: 'bad', 6: 'good', 7: 'good', 8: 'good'})

# Encode binary labels
data['quality'] = data['quality'].map({'bad': 0, 'good': 1})

# 1. Pearson and Spearman correlation with quality
print("Pearson Correlation with Quality:")
for col in data.columns[:-1]:
    corr, _ = pearsonr(data[col], data['quality'])
    print(f"{col}: {corr:.3f}")

print("\nSpearman Correlation with Quality:")
for col in data.columns[:-1]:
    corr, _ = spearmanr(data[col], data['quality'])
    print(f"{col}: {corr:.3f}")

# 2. Hypothesis Testing: Does alcohol affect wine quality?
good_wine = data[data['quality'] == 1]['alcohol']
bad_wine = data[data['quality'] == 0]['alcohol']

t_stat, p_val = ttest_ind(good_wine, bad_wine)
print(f"\nT-test for Alcohol between Good and Bad Wines:")
print(f"T-statistic: {t_stat:.3f}, P-value: {p_val:.5f}")

if p_val < 0.05:
    print("✅ Alcohol content significantly affects wine quality (reject H₀)")
else:
    print("❌ No significant difference in alcohol content (fail to reject H₀)")

# Optional: Visualize alcohol distribution
sns.boxplot(x='quality', y='alcohol', data=data)
plt.title("Alcohol Content by Wine Quality")
plt.show()